"""initial mvp schema

Revision ID: 4cd3f432915c
Revises: 
Create Date: 2026-09-28 23:20:21.651244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd3f432915c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_sources',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('campaign', sa.String(length=128), nullable=True),
    sa.Column('placement', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('flyer', 'site', 'vk', 'instagram', 'tg_channel', 'referral', 'offline_event', 'other')", name=op.f('ck_acquisition_sources_source_channel')),
    sa.CheckConstraint("code ~ '^[A-Za-z0-9_-]{1,50}$'", name=op.f('ck_acquisition_sources_code_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acquisition_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_acquisition_sources_code'))
    )
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'manager', 'viewer')", name=op.f('ck_admins_admin_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_admins_telegram_id'))
    )
    op.create_table('lecturers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('regalia', sa.Text(), nullable=True),
    sa.Column('bio_html', sa.Text(), nullable=True),
    sa.Column('photo_file_id', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecturers'))
    )
    op.create_table('legal_documents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('privacy_policy', 'pd_consent', 'marketing_consent', 'offer')", name=op.f('ck_legal_documents_legal_document_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_documents')),
    sa.UniqueConstraint('type', 'version', name=op.f('uq_legal_documents_type_version'))
    )
    op.create_index('uq_legal_documents_current_type', 'legal_documents', ['type'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('title', name=op.f('uq_positions_title'))
    )
    op.create_table('programs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('short_description', sa.String(length=512), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('program_html', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('default_format', sa.String(length=32), server_default='offline', nullable=False),
    sa.Column('duration_hours', sa.SmallInteger(), nullable=True),
    sa.Column('cover_file_id', sa.String(length=256), nullable=True),
    sa.Column('nmo_points', sa.SmallInteger(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_format IN ('online', 'offline', 'hybrid')", name=op.f('ck_programs_default_format')),
    sa.CheckConstraint("level IN ('basic', 'advanced')", name=op.f('ck_programs_program_level')),
    sa.CheckConstraint('duration_hours > 0', name=op.f('ck_programs_duration_hours_positive')),
    sa.CheckConstraint('nmo_points >= 0', name=op.f('ck_programs_nmo_points_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs')),
    sa.UniqueConstraint('slug', name=op.f('uq_programs_slug'))
    )
    op.create_table('specialties',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties')),
    sa.UniqueConstraint('title', name=op.f('uq_specialties_title'))
    )
    op.create_table('venues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('map_url', sa.String(length=512), nullable=True),
    sa.Column('directions_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('tg_first_name', sa.String(length=64), nullable=True),
    sa.Column('tg_last_name', sa.String(length=64), nullable=True),
    sa.Column('tg_language_code', sa.String(length=16), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('name_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('workplace_raw', sa.String(length=256), nullable=True),
    sa.Column('practice_since_year', sa.SmallInteger(), nullable=True),
    sa.Column('profile_status', sa.String(length=32), server_default='new', nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('referred_by_client_id', sa.BigInteger(), nullable=True),
    sa.Column('first_source_id', sa.BigInteger(), nullable=True),
    sa.Column('is_bot_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bot_blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("profile_status IN ('new', 'partial', 'completed')", name=op.f('ck_clients_profile_status')),
    sa.CheckConstraint('practice_since_year BETWEEN 1950 AND 2100', name=op.f('ck_clients_practice_since_year_range')),
    sa.CheckConstraint('referred_by_client_id <> id', name=op.f('ck_clients_not_self_referred')),
    sa.ForeignKeyConstraint(['first_source_id'], ['acquisition_sources.id'], name=op.f('fk_clients_first_source_id_acquisition_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referred_by_client_id'], ['clients.id'], name=op.f('fk_clients_referred_by_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('referral_code', name=op.f('uq_clients_referral_code')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_clients_telegram_id'))
    )
    op.create_index('ix_clients_created_at', 'clients', ['created_at'], unique=False)
    op.create_index('ix_clients_email_lower', 'clients', [sa.literal_column('lower(email)')], unique=False)
    op.create_index(op.f('ix_clients_first_source_id'), 'clients', ['first_source_id'], unique=False)
    op.create_index(op.f('ix_clients_referred_by_client_id'), 'clients', ['referred_by_client_id'], unique=False)
    op.create_index('uq_clients_phone_active', 'clients', ['phone'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('program_specialties',
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('specialty_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_program_specialties_program_id_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_program_specialties_specialty_id_specialties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', 'specialty_id', name=op.f('pk_program_specialties'))
    )
    op.create_index('ix_program_specialties_specialty_id', 'program_specialties', ['specialty_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=True),
    sa.Column('online_url', sa.String(length=512), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('title_override', sa.String(length=256), nullable=True),
    sa.Column('cover_file_id', sa.String(length=256), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('online', 'offline', 'hybrid')", name=op.f('ck_sessions_session_format')),
    sa.CheckConstraint("status IN ('draft', 'announced', 'registration_open', 'waitlist', 'full', 'registration_closed', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_sessions_session_status')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_sessions_capacity_positive')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_sessions_dates_order')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_sessions_program_id_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_sessions_venue_id_venues'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_program_id'), 'sessions', ['program_id'], unique=False)
    op.create_index('ix_sessions_status_start_date', 'sessions', ['status', 'start_date'], unique=False)
    op.create_index(op.f('ix_sessions_venue_id'), 'sessions', ['venue_id'], unique=False)
    op.create_table('client_consents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='telegram_bot', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('telegram_bot', 'site', 'admin')", name=op.f('ck_client_consents_consent_source')),
    sa.CheckConstraint("type IN ('personal_data', 'marketing')", name=op.f('ck_client_consents_consent_type')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_consents_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['legal_documents.id'], name=op.f('fk_client_consents_document_id_legal_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_consents'))
    )
    op.create_index('ix_client_consents_client_id_type', 'client_consents', ['client_id', 'type'], unique=False)
    op.create_index(op.f('ix_client_consents_document_id'), 'client_consents', ['document_id'], unique=False)
    op.create_index('uq_client_consents_active', 'client_consents', ['client_id', 'type'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('client_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_events_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_events'))
    )
    op.create_index('ix_client_events_client_id_created_at', 'client_events', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_client_events_type_created_at', 'client_events', ['type', 'created_at'], unique=False)
    op.create_table('client_positions',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_positions_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_client_positions_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'position_id', name=op.f('pk_client_positions'))
    )
    op.create_index('ix_client_positions_position_id', 'client_positions', ['position_id'], unique=False)
    op.create_table('client_source_touches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_payload', sa.String(length=64), nullable=False),
    sa.Column('is_first', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_source_touches_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['acquisition_sources.id'], name=op.f('fk_client_source_touches_source_id_acquisition_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_source_touches'))
    )
    op.create_index(op.f('ix_client_source_touches_client_id'), 'client_source_touches', ['client_id'], unique=False)
    op.create_index('ix_client_source_touches_source_id_created_at', 'client_source_touches', ['source_id', 'created_at'], unique=False)
    op.create_table('client_specialties',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('specialty_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_specialties_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_client_specialties_specialty_id_specialties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'specialty_id', name=op.f('pk_client_specialties'))
    )
    op.create_index('ix_client_specialties_specialty_id', 'client_specialties', ['specialty_id'], unique=False)
    op.create_table('price_options',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'RUB'"), nullable=False),
    sa.Column('unit', sa.String(length=32), server_default='per_person', nullable=False),
    sa.Column('min_seats', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_seats', sa.SmallInteger(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seats_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('full', 'theory', 'practice', 'group', 'early_bird', 'other')", name=op.f('ck_price_options_price_kind')),
    sa.CheckConstraint("unit IN ('per_person', 'per_group')", name=op.f('ck_price_options_price_unit')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_price_options_amount_non_negative')),
    sa.CheckConstraint('max_seats >= min_seats', name=op.f('ck_price_options_seats_range')),
    sa.CheckConstraint('min_seats >= 1', name=op.f('ck_price_options_min_seats_positive')),
    sa.CheckConstraint('seats_limit > 0', name=op.f('ck_price_options_seats_limit_positive')),
    sa.CheckConstraint('valid_until > valid_from', name=op.f('ck_price_options_validity_order')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_price_options_session_id_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_options'))
    )
    op.create_index(op.f('ix_price_options_session_id'), 'price_options', ['session_id'], unique=False)
    op.create_table('program_interests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_program_interests_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_program_interests_program_id_programs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_interests')),
    sa.UniqueConstraint('client_id', 'program_id', name=op.f('uq_program_interests_client_id_program_id'))
    )
    op.create_index(op.f('ix_program_interests_program_id'), 'program_interests', ['program_id'], unique=False)
    op.create_table('session_days',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('topic', sa.String(length=256), nullable=True),
    sa.Column('venue_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_session_days_times_order')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_days_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_session_days_venue_id_venues'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_days'))
    )
    op.create_index('ix_session_days_session_id_date', 'session_days', ['session_id', 'date'], unique=False)
    op.create_index(op.f('ix_session_days_venue_id'), 'session_days', ['venue_id'], unique=False)
    op.create_table('session_lecturers',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('lecturer_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], name=op.f('fk_session_lecturers_lecturer_id_lecturers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_lecturers_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'lecturer_id', name=op.f('pk_session_lecturers'))
    )
    op.create_index('ix_session_lecturers_lecturer_id', 'session_lecturers', ['lecturer_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('price_option_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='application', nullable=False),
    sa.Column('payment_status', sa.String(length=32), server_default='unpaid', nullable=False),
    sa.Column('requested_seats', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='bot', nullable=False),
    sa.Column('client_comment', sa.Text(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('unpaid', 'partial', 'paid', 'refunded')", name=op.f('ck_enrollments_payment_status')),
    sa.CheckConstraint("source IN ('bot', 'admin', 'site', 'phone')", name=op.f('ck_enrollments_enrollment_source')),
    sa.CheckConstraint("status IN ('application', 'confirmed', 'waitlist', 'cancelled_by_client', 'cancelled_by_admin', 'attended', 'no_show', 'completed')", name=op.f('ck_enrollments_enrollment_status')),
    sa.CheckConstraint('requested_seats >= 1', name=op.f('ck_enrollments_requested_seats_positive')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_enrollments_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['price_option_id'], ['price_options.id'], name=op.f('fk_enrollments_price_option_id_price_options'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_enrollments_session_id_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments'))
    )
    op.create_index(op.f('ix_enrollments_client_id'), 'enrollments', ['client_id'], unique=False)
    op.create_index(op.f('ix_enrollments_session_id'), 'enrollments', ['session_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index('uq_enrollments_client_id_session_id_active', 'enrollments', ['client_id', 'session_id'], unique=True, postgresql_where=sa.text("status NOT IN ('cancelled_by_client', 'cancelled_by_admin')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_enrollments_client_id_session_id_active', table_name='enrollments', postgresql_where=sa.text("status NOT IN ('cancelled_by_client', 'cancelled_by_admin')"))
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_session_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_client_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_session_lecturers_lecturer_id', table_name='session_lecturers')
    op.drop_table('session_lecturers')
    op.drop_index(op.f('ix_session_days_venue_id'), table_name='session_days')
    op.drop_index('ix_session_days_session_id_date', table_name='session_days')
    op.drop_table('session_days')
    op.drop_index(op.f('ix_program_interests_program_id'), table_name='program_interests')
    op.drop_table('program_interests')
    op.drop_index(op.f('ix_price_options_session_id'), table_name='price_options')
    op.drop_table('price_options')
    op.drop_index('ix_client_specialties_specialty_id', table_name='client_specialties')
    op.drop_table('client_specialties')
    op.drop_index('ix_client_source_touches_source_id_created_at', table_name='client_source_touches')
    op.drop_index(op.f('ix_client_source_touches_client_id'), table_name='client_source_touches')
    op.drop_table('client_source_touches')
    op.drop_index('ix_client_positions_position_id', table_name='client_positions')
    op.drop_table('client_positions')
    op.drop_index('ix_client_events_type_created_at', table_name='client_events')
    op.drop_index('ix_client_events_client_id_created_at', table_name='client_events')
    op.drop_table('client_events')
    op.drop_index('uq_client_consents_active', table_name='client_consents', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_client_consents_document_id'), table_name='client_consents')
    op.drop_index('ix_client_consents_client_id_type', table_name='client_consents')
    op.drop_table('client_consents')
    op.drop_index(op.f('ix_sessions_venue_id'), table_name='sessions')
    op.drop_index('ix_sessions_status_start_date', table_name='sessions')
    op.drop_index(op.f('ix_sessions_program_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_program_specialties_specialty_id', table_name='program_specialties')
    op.drop_table('program_specialties')
    op.drop_index('uq_clients_phone_active', table_name='clients', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_clients_referred_by_client_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_first_source_id'), table_name='clients')
    op.drop_index('ix_clients_email_lower', table_name='clients')
    op.drop_index('ix_clients_created_at', table_name='clients')
    op.drop_table('clients')
    op.drop_table('venues')
    op.drop_table('specialties')
    op.drop_table('programs')
    op.drop_table('positions')
    op.drop_index('uq_legal_documents_current_type', table_name='legal_documents', postgresql_where=sa.text('is_current'))
    op.drop_table('legal_documents')
    op.drop_table('lecturers')
    op.drop_table('admins')
    op.drop_table('acquisition_sources')
    # ### end Alembic commands ###
